name: Deploy Hexo

on:
  push:
    branches:
      - master
      - games

permissions:
  contents: write  # 必须加 否则 github_token 没权限 push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Hexo
        run: |
          npm install -g hexo-cli
          npm install

      - name: Build
        run: |
          hexo clean
          hexo generate

      - name: Fetch games branch
        run: |
          mkdir -p ./public/games
          cd ./public/games
          git init
          git remote add origin https://github.com/${{ github.repository }}.git
          git fetch origin games
          git checkout origin/games -- .   

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages

